language: php

matrix:
  allow_failures:
    - php: 5.6
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
      env: SUBMODULE_TEST=yes
    - php: 5.6

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - >
    if [[ "$TRAVIS_PHP_VERSION" = "5.3" || "$TRAVIS_PHP_VERSION" = "5.4" ]]; then
        pecl install igbinary > /dev/null;
    fi
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - chmod a+x typo3/sysext/core/Build/Scripts/*
  - sudo apt-get install parallel
  - composer self-update
  - composer install

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find . -wholename '*typo3/sysext/*/Tests/Functional/*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {}'
  - >
    echo;
    echo "Running php lint";
    find typo3/ -name \*.php -not -path "typo3/contrib/vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running XLF checker";
    ./typo3/sysext/core/Build/Scripts/xlfcheck.sh
  - >
    if [[ "$SUBMODULE_TEST" == "yes" ]]; then
        echo;
        echo "Running git submodule check";
        /bin/bash -c "
            if [[ `git submodule status 2>&1 | wc -l` -ne 0 ]]; then
                echo \"Found a submodule definition in repository\";
                exit 99;
            fi
        "
    fi
