language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

services:
  - memcached

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - sudo apt-get install parallel
  - git clone --single-branch --branch master --depth 1 git://github.com/lolli42/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
  - installPhpModule -y memcache
  - installPhpModule redis
  - mkdir fileadmin uploads typo3temp
  - mv build-environment/typo3conf .
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3CMS/Extensions/phpunit.git typo3conf/ext/phpunit/

script:
  - >
	echo "Running unit tests"
	./typo3conf/ext/phpunit/Composer/vendor/bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml
  - >
	echo "Running functional tests";
	./typo3conf/ext/phpunit/Composer/vendor/bin/phpunit -c typo3/sysext/core/Build/FunctionalTests.xml
  - >
	echo "Running php lint";
	if find typo3/ -name \*.php | parallel --gnu --keep-order 'php -l {}' > /tmp/errors
	then
		exit 0
	else
		grep -v "No syntax errors detected in" /tmp/errors
		exit 99
	fi
