language: php

matrix:
  fast_finish: true

  include:
    - php: 7
      env: UNIT_TESTS=no

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: rIsY51ZUrqlySRVH3RZughD7V5P5gndvdShYpnnvd+DOoHKAdDU3GwMP0NGZXQj8lo8pL+F0ysEWuT5dhTE5HXj7ZsTLz5o3pDJzark64ymmOmzVlakccLecvatpZ+gv3K5c14huzUF7yn7TZ7rEoUBxK3kxbW8UrqLIbhCel5o=

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://www.t3bot.de/hooks/travis/index.php
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - phpenv config-rm xdebug.ini
  - >
    if [[ "$TRAVIS_PHP_VERSION" < "7" && -e ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ]]; then
        echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - >
    ./bin/selenium-server-standalone &
    php -S localhost:8000 &
    sleep 20;
    /bin/netstat -anp;
    mysql -e 'create database acceptance';
    mysql acceptance < typo3/sysext/core/ext_tables.sql;
    mkdir -p typo3temp/var/logs/codeception/ typo3conf/ext;
    cp typo3/sysext/core/Build/Configuration/Acceptance/TravisLocalConfiguration.php typo3conf/LocalConfiguration.php;
    cp typo3/sysext/core/Build/Configuration/Acceptance/TravisPackageStates.php typo3conf/PackageStates.php;
    wget http://localhost:8000/typo3/index.php;
    head -n 120 index.php.1;
    ./bin/codecept run acceptance -c typo3/sysext/core/Build/AcceptanceTests.yml typo3/sysext/core/Tests/Acceptance;
    cat typo3temp/var/logs/codeception/BackendLoginMouseOverCept.fail.html
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml
    fi
  - >
    if [[ "$FUNCTIONAL_TESTS" == "yes" ]]; then
        echo;
        export typo3DatabaseName="typo3";
        export typo3DatabaseHost="localhost";
        export typo3DatabaseUsername="root";
        export typo3DatabasePassword="";
        find . -wholename '*typo3/sysext/*/Tests/Functional/*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; ./bin/phpunit -c typo3/sysext/core/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$PHP_LINT" == "yes" ]]; then
        echo;
        echo "Running php lint";
        find typo3/ -name \*.php -not -path "vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
    fi
  - >
    if [[ "$XLF_CHECK" == "yes" ]]; then
        echo;
        echo "Running XLF checker";
        ./typo3/sysext/core/Build/Scripts/xlfcheck.sh
    fi
  - >
      if [[ "$SUBMODULE_TEST" == "yes" ]]; then
          echo;
          echo "Running git submodule check";
          /bin/bash -c "
              if [[ `git submodule status 2>&1 | wc -l` -ne 0 ]]; then
                  echo \"Found a submodule definition in repository\";
                  exit 99;
              fi
          "
      fi