language: php

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
  include:
    - php: 5.5
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes XLF_CHECK=yes

services:
  - memcached
  - redis-server

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - mkdir parallel && cd parallel && wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 && tar xvf parallel-latest.tar.bz2 -C . --strip-components=1 && ./configure && make && cd ..
  - >
    ( if [[ "$FUNCTIONAL_TESTS" == "yes" ]]; then
      mkdir /dev/shm/typo3ramdisk;
      chmod 700 /dev/shm/typo3ramdisk;
      mysqld_safe --defaults-file=typo3/sysext/core/Build/TravisCi/my.cnf --skip-grant-tables;
    fi ) &
  - rm -rf typo3/sysext/compatibility6
  - composer self-update
  - composer install

script:
  - >
    ls -lR /tmp/;
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export typo3DatabaseSocket=/dev/shm/typo3ramdisk/mysqld-testing.sock;
    export typo3DatabaseHost="localhost";
    export typo3DatabaseName="typo3";
    find . -wholename '*typo3/sysext/*/Tests/Functional/*Test.php' | ./parallel/src/parallel -P 8 --gnu --will-cite 'typo3/sysext/core/Build/TravisCi/FunctionalTests.sh {}';
    ls -lR /tmp/;
    ls -lR /dev/shm/typo3ramdisk;