language: php

matrix:
  fast_finish: true

  include:
    - php: 7
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes ACCEPTANCE_TESTS=yes PHP_LINT=yes XLF_CHECK=yes SUBMODULE_TEST=yes

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: rIsY51ZUrqlySRVH3RZughD7V5P5gndvdShYpnnvd+DOoHKAdDU3GwMP0NGZXQj8lo8pL+F0ysEWuT5dhTE5HXj7ZsTLz5o3pDJzark64ymmOmzVlakccLecvatpZ+gv3K5c14huzUF7yn7TZ7rEoUBxK3kxbW8UrqLIbhCel5o=

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://www.t3bot.de/hooks/travis/index.php
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - phpenv config-rm xdebug.ini
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install

script:
  - >
    if [[ "$FUNCTIONAL_TESTS" == "yes" ]]; then
        for I in $(seq 1 180); do echo $I; echo processes: `ps x | wc -l`; sleep 1; done &
        echo;
        export typo3DatabaseName="typo3";
        export typo3DatabaseHost="localhost";
        export typo3DatabaseUsername="root";
        export typo3DatabasePassword="";
        find . -wholename '*typo3/sysext/*/Tests/Functional/*Test.php' | parallel --jobs 4 --gnu 'echo; echo "Running functional test suite {}"; ./bin/phpunit -c typo3/sysext/core/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$PHP_LINT" == "yes" ]]; then
        for I in $(seq 1 60); do echo $I; echo processes: `ps x | wc -l`; sleep 1; done &
        echo;
        echo "Running php lint";
        find typo3/ -name \*.php -not -path "vendor/*" | parallel --jobs 4 --gnu php -d display_errors=stderr -l {} > /dev/null \;
    fi
