language: php

matrix:
  fast_finish: true

  include:
    - php: 7
      env: UNIT_TESTS=yes

sudo: false

addons:
  apt:
    packages:
      - language-pack-de

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://www.t3bot.de/hooks/travis/index.php
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - COMPOSER_ROOT_VERSION=dev-master composer install

script:
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      ./bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
    fi
