language: php

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
  include:
    - php: 5.5
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes XLF_CHECK=yes
    - php: 5.6
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes
    - php: hhvm-nightly
      env: UNIT_TESTS=yes

services:
  - memcached
  - redis-server

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

script:
  - >
    mount
  - >
    cat /etc/fstab

