language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - composer self-update
  - composer --dev install
  - git clone --single-branch --branch master --depth 1 git://github.com/lolli42/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; echo "apc.slam_defense=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then pecl install igbinary > /dev/null; echo "extension = igbinary.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mv build-environment/typo3conf .
  - mkdir fileadmin uploads typo3temp typo3conf/ext

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml
#  - >
#    echo;
#    echo "Running functional tests";
#    ./bin/phpunit -c typo3/sysext/core/Build/FunctionalTests.xml
#  - >
#    echo;
#    echo "Running php lint";
#    /bin/bash -c "
#        if ! find typo3/ -name \*.php -print0 | xargs -0 -n1 -P8 php -l >/tmp/errors 2>&1; then
#            grep -v \"No syntax errors detected in\" /tmp/errors;
#            exit 99;
#        fi
#    "
