language: php

matrix:
  fast_finish: true

  include:
    - php: 7
      env: UNIT_TESTS=yes ACCEPTANCE_TESTS=no

sudo: false

addons:
  apt:
    packages:
      - parallel
      - ack-grep
      - nginx
      - realpath

cache:
  - apt
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: rIsY51ZUrqlySRVH3RZughD7V5P5gndvdShYpnnvd+DOoHKAdDU3GwMP0NGZXQj8lo8pL+F0ysEWuT5dhTE5HXj7ZsTLz5o3pDJzark64ymmOmzVlakccLecvatpZ+gv3K5c14huzUF7yn7TZ7rEoUBxK3kxbW8UrqLIbhCel5o=

services:
  - memcached
  - redis-server

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://www.t3bot.de/hooks/travis/index.php
    on_success: always
    on_failure: always
    on_start: never

before_script:
  - phpenv config-rm xdebug.ini
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install

script:
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml typo3/sysext/core/Tests/Unit/Authentication/AbstractUserAuthenticationTest.php
    fi
  - >
    if [[ "$ACCEPTANCE_TESTS" == "yes" ]]; then
        export _JAVA_OPTIONS="-Xms1024m -Xmx1024m";
        ./bin/selenium-server-standalone >/dev/null 2>&1 &
        php -S 0.0.0.0:8000 >/dev/null 2>&1 &
        sleep 5;
        export typo3DatabaseName="typo3";
        export typo3DatabaseHost="localhost";
        export typo3DatabaseUsername="root";
        export typo3DatabasePassword="";
        ./bin/codecept run Acceptance -c typo3/sysext/core/Build/AcceptanceTests.yml --debug
    fi
