language: php

matrix:
  fast_finish: true

  include:
    - php: 7

sudo: required

addons:
  apt:
    packages:
      - language-pack-de
  sonarcloud:
    organization: "typo3"

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.sonar/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://www.t3bot.de/hooks/travis/index.php
    on_success: always
    on_failure: always
    on_start: never

script:
  - sonar-scanner -Dproject.settings=Build/.sonar-project.properties
