language: php

matrix:
  fast_finish: true

  include:
    - php: 7
      env: UNIT_TESTS=no ACCEPTANCE_TESTS=yes

sudo: false

addons:
  apt:
    packages:
      - parallel
      - ack-grep
      - nginx
      - realpath

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    secure: rIsY51ZUrqlySRVH3RZughD7V5P5gndvdShYpnnvd+DOoHKAdDU3GwMP0NGZXQj8lo8pL+F0ysEWuT5dhTE5HXj7ZsTLz5o3pDJzark64ymmOmzVlakccLecvatpZ+gv3K5c14huzUF7yn7TZ7rEoUBxK3kxbW8UrqLIbhCel5o=

services:
  - memcached
  - redis-server

before_script:
  - phpenv config-rm xdebug.ini
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer install

script:
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml typo3/sysext/core/Tests/Unit/Authentication/AbstractUserAuthenticationTest.php
    fi
  - >
    if [[ "$ACCEPTANCE_TESTS" == "yes" ]]; then
        typo3/sysext/core/Build/Configuration/TravisNginxFpm/ConfigureStartNginxFpm.sh
        mkdir -p typo3temp/var/tests;
        export typo3DatabaseName="typo3";
        export typo3DatabaseHost="localhost";
        export typo3DatabaseUsername="root";
        export typo3DatabasePassword="";
        ./bin/codecept run Acceptance -c typo3/sysext/core/Build/AcceptanceTests.yml
    fi
